platform :ios, '13.0'
 

def commonPods
  pod 'MJExtension', '3.2.2'
  pod 'Toast', '~> 4.0.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'XLForm', '~> 4.3'
  pod 'CocoaLumberjack'
  pod 'Masonry'
  pod 'MJRefresh', '3.7.2'
  pod 'SDWebImage', '5.12.1'
end

target 'Demo_OC' do
  use_frameworks!
  # Pods for Demo_OC
  commonPods
  
  pod 'ToBid-iOS-RC', '5.3.0', :subspecs => [
    'BidResultAdapter',
    'CSJAdapter',
    'GromoreAdapter',
    'GDTAdapter',
    'KSAdapter',
    'BaiduAdapter',
    'AdScopeAdapter',
    'MSAdAdapter',
    'MercuryAdapter',
    'OctopusAdapter',
    'AdmobAdapter',
    'JADYunAdapter',
    'VungleAdapter',
    'UnityAdsAdapter',
    'AppLovinAdapter',
    'IronSourceAdapter',
    'QuMengAdapter',
    'AdScopeAdapter',
  ]
  pod 'ToBidMentaCNAdapter', :path => '../'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
         end
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
